### ISSUE TITLE
Nikols Vasić is always the author in the log

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer-Taxonomy#10]
U taksonomskoj bazi stoji:
 31.10.2022 01:00 Miloš Popović je изменио/ла Црвене листе: Promenjena hr crvena lista u CR 

U lokalnim bazama to izgleda ovako:
 31.10.2022 01:00 Nikola Vasic je изменио/ла : Promenjena hr crvena lista u CR 

Treba da bude:
 31.10.2022 01:00 [из таксономске базе] Miloš Popović je изменио/ла : Promenjena hr crvena lista u CR

**Comment by nvasic88** [comment]
Da, ovo je bio jedan problem koji sam privremeno rešio povezivanjem sa prvim ID-em korisnika u lokalnoj bazi.

Korisnici taksonomske baze nisu istovremeno i korisnici lokalnih baza, i  za sada nisam pokušavao povezivanje korisnika sa lokalnim bazama. 

Ukoliko se ne poveže u lokalnoj bazi sa nekim korisnikom, onda se izmena ne prikazuje u listi izmena.

Ili ćemo dodati korisnika nalik "Taxonomy" u svakoj lokalnoj bazi i nekako povezati izmene sa tim nalogom, ili moram da radim neku vrstu uparivanja korisnika.. za sada nisam siguran šta je najbolji pristup.

**Comment by gpopac** [comment]
Možda bi Nenad @nikazooz mogao da da sugestiju. Meni su obe opcije prihvatljive. Čak mi je prihvatljivo i da se dalje ne sinhronizuje log izmena nakon što se lokalne baze povežu sa taksonomskom. U tom slučaju bi za detalje oko toga ko je i šta radio u taksonomiji morali da pogledamo taksonomsku bazu.

**Comment by nikazooz** [comment]
Slažem se više za varijantu da log bude u taksonomskoj bazi.
