### ISSUE TITLE
Sinonim treba da ima dva polja umesto jednog

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer-Taxonomy#7]
Za sinonim sada postoji sam ojedno polje gde se upisuje ceo latinski naziv. Treba da razdvojiti u dva polja — naziv i autor. Pretraga i prikaz u aplikacijama za telefone će biti preko naziva ovog polja, nećemo krositi i autora, takođe i buduće implementacije pretrage po sinonimima na vebu neće koristiti ime autora, ali se ono može prikazivati u nekim slučajevima (mada čak i kad se prikazuje naziv ide italik a autor normalnim fontom).

**Comment by nvasic88** [comment]
Ok, ovo ću srediti taman pre implementacije u lokalnoj bazi.

Da li su oba polja obavezna prilikom unosa sinonima?

**Comment by gpopac** [comment]
Genralno, pravilo je da idu zajedno, ali mislim da u nekim slučajevima nećemo imati ime autroa. Tako da stavi da je prvo polje obavezno, a da drugo nije.
