### ISSUE TITLE
Ne sinhronizuje neka polja crvene liste na sr verziji

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer-Taxonomy#8]
Za Pieris rapae postoji status na crvenim listama u Srbiji i Evropskoj uniji (http://taxonomy.nvasic.com/sr/admin/taxa/162/edit) ali on nije ažuriran u srpskoj bazi (http://rs.singiweb.cc/sr/admin/taxa/20651/edit).

**Comment by nvasic88** [comment]
Da, ali iz razloga što u lokalnoj bazi RS ne postoji Evropska Unija i Hrvatska kao crvene liste...

Biologer Taxonomija mora da u sebi ima sve crvene liste koje postoje u svim lokalnim bazama, dok obrnuto to nije slučaj.

Ukoliko smatraš da je potrebno i obrnuto, onda mogu da se pozabavim ovim problemom...

> Za Pieris rapae postoji status na crvenim listama u Srbiji i Evropskoj uniji (http://taxonomy.nvasic.com/sr/admin/taxa/162/edit) ali on nije ažuriran u srpskoj bazi (http://rs.singiweb.cc/sr/admin/taxa/20651/edit).

**Comment by gpopac** [comment]
@nvasic88 zapravo mislim da si ovo dobro rešio. Moja greška.
